import { Business } from '../types/business'

export const mockBusinesses: Business[] = [
    {
        place_id: 'ChIJfadx80xYzpQRyHnuTnmQmDA',
        name: 'Famiglia Mancini Trattoria',
        address: 'Rua Avanhandava, 81, Bela Vista - Centro Histórico, São Paulo - SP',
        phone: '(11) 3256-4320',
        rating: 4.7,
        website: 'http://www.famigliamancini.com.br/',
        type: 'Restaurante',
        accessible: true,
        response_time: 1244.15,
        status_code: 200,
    },
    {
        place_id: 'ChIJn8NM579QzpQRWT06N8pdDgQ',
        name: 'Vicolo Nostro',
        address: 'Rua Jataituba, 29 - Cidade Monções, São Paulo - SP',
        phone: '(11) 5561-5287',
        rating: 4.7,
        website: 'https://vicolonostro.com.br/',
        type: 'Restaurante',
        accessible: false,
        response_time: 1072.11,
        status_code: 406,
    },
    {
        place_id: 'ChIJz36TCeJZzpQR4vkgCNah0Dw',
        name: 'Terraço Itália',
        address: 'Av. Ipiranga, 344 - 41º andar - República, São Paulo - SP',
        phone: '(11) 2189-2929',
        rating: 4.6,
        website: 'http://www.terracoitalia.com.br/',
        type: 'Restaurante',
        accessible: true,
        response_time: 1507.6,
        status_code: 200,
    },
    {
        place_id: 'ChIJzzHeXrlZzpQRO731LSDui34',
        name: 'Osteria Generale - Bela Vista',
        address: 'R. Dr. Fausto Ferraz, 163 - Bela Vista, São Paulo - SP',
        phone: '(11) 3253-5572',
        rating: 4.7,
        website: 'http://www.generale.com.br/',
        type: 'Restaurante',
        accessible: false,
        response_time: null,
        status_code: null,
    },
    {
        place_id: 'ChIJXXAo52dXzpQRdeK4IWo4W2s',
        name: 'Modern Mamma Osteria',
        address: 'R. Manuel Guedes, 160 - Itaim Bibi, São Paulo - SP',
        phone: null,
        rating: 4.7,
        website: 'http://momaosteria.com.br/',
        type: 'Restaurante',
        accessible: false,
        response_time: 1279.69,
        status_code: 404,
    },
    {
        place_id: 'ChIJyd9bvX3ZmwARg0FwSGz0WZM',
        name: 'Hilton Barra Rio de Janeiro',
        address: 'Av. Engenheiro Carlos Carvalho, 1430 - Barra da Tijuca, Rio de Janeiro - RJ',
        phone: '(21) 3348-1000',
        rating: 4.7,
        website: 'https://www.hilton.com/en/hotels/rioabhh-hilton-barra-rio-de-janeiro/',
        type: 'Hotel',
        accessible: false,
        response_time: 1418.27,
        status_code: 403,
    },
    {
        place_id: 'ChIJ_4vLdmF_mQARxM9MStynroU',
        name: 'Hotel Atlântico Business',
        address: 'R. Sen. Dantas, 25 - Centro, Rio de Janeiro - RJ',
        phone: '(21) 3626-7000',
        rating: 3.9,
        website: 'https://www.booking.com/hotel/br/atlantico-business.xb.html',
        type: 'Hotel',
        accessible: false,
        response_time: 1406.59,
        status_code: 202,
    },
    {
        place_id: 'ChIJ7f-3y5_WmwARzEMl9WJga-8',
        name: 'Hotel Nacional Rio de Janeiro',
        address: 'Av. Niemeyer, 769 - São Conrado, Rio de Janeiro - RJ',
        phone: '0800 000 1563',
        rating: 4.5,
        website: 'https://hotelnacionalriodejaneiro.com/',
        type: 'Hotel',
        accessible: true,
        response_time: 636.13,
        status_code: 200,
    },
    {
        place_id: 'ChIJjZJPDlTVmwARroitzBhRLu8',
        name: 'Copacabana Palace, A Belmond Hotel',
        address: 'Av. Atlântica, 1702 - Copacabana, Rio de Janeiro - RJ',
        phone: '(21) 2141-8990',
        rating: 4.8,
        website: 'https://www.belmond.com/hotels/south-america/brazil/rio-de-janeiro/belmond-copacabana-palace/',
        type: 'Hotel',
        accessible: true,
        response_time: 1666.01,
        status_code: 200,
    },
    {
        place_id: 'ChIJixfp_YZ_mQARbyWGzuRH3-s',
        name: 'Por el Mundo Hostel',
        address: 'R. da Lapa, 207 - Lapa, RJ',
        phone: '(21) 99527-5145',
        rating: 4.2,
        website: 'https://porelmundohostel.com.br/',
        type: 'Hotel',
        accessible: false,
        response_time: 993.78,
        status_code: 406,
    },
    {
        place_id: 'mock-clinic-001',
        name: 'Clínica São Lucas',
        address: 'Rua das Flores, 450 - Jardins, São Paulo - SP',
        phone: '(11) 4002-8922',
        rating: 4.5,
        website: 'https://clinicasaolucas.com.br/',
        type: 'Saúde',
        accessible: true,
        response_time: 823.0,
        status_code: 200,
    },
    {
        place_id: 'mock-edu-001',
        name: 'Colégio Progresso',
        address: 'Av. Paulista, 900 - Bela Vista, São Paulo - SP',
        phone: '(11) 3200-1234',
        rating: 4.4,
        website: 'https://colegioprogressosp.com.br/',
        type: 'Educação',
        accessible: true,
        response_time: 542.0,
        status_code: 200,
    },
    // Itapema - SC Businesses
    {
        place_id: 'itapema-001',
        name: 'Itapema Tatuagem & Piercing',
        address: 'Av. Nereu Ramos, 1200 - Meia Praia, Itapema - SC',
        phone: '(47) 3368-1234',
        rating: 4.9,
        website: 'https://itapematattoo.com.br/',
        type: 'Serviços',
        accessible: true,
        response_time: 450.0,
        status_code: 200,
    },
    {
        place_id: 'itapema-002',
        name: 'Remoção de Tatuagem Meia Praia',
        address: 'Rua 250, 45 - Meia Praia, Itapema - SC',
        phone: '(47) 99123-4567',
        rating: 4.8,
        website: 'https://remocaotatuagemitapema.com.br/',
        type: 'Saúde',
        accessible: true,
        response_time: 1200.0,
        status_code: 200,
    },
    {
        place_id: 'itapema-003',
        name: 'Hotel Baía Norte Itapema',
        address: 'Av. Beira Mar, 500 - Centro, Itapema - SC',
        phone: '(47) 3368-5500',
        rating: 4.6,
        website: 'https://hotelbaianorte.com.br/',
        type: 'Hotel',
        accessible: false,
        response_time: 3200.0,
        status_code: 504,
    },
    {
        place_id: 'itapema-004',
        name: 'Restaurante Indaiá',
        address: 'R. 900, 1300 - Sertão do Trombudo, Itapema - SC',
        phone: '(47) 3368-2745',
        rating: 4.7,
        website: 'https://restauranteindaia.com.br/',
        type: 'Restaurante',
        accessible: true,
        response_time: 1540.0,
        status_code: 200,
    },
    {
        place_id: 'itapema-005',
        name: 'Clínica Estética Itapema',
        address: 'Segunda Avenida, 800 - Meia Praia, Itapema - SC',
        phone: '(47) 3368-9988',
        rating: 4.5,
        website: 'https://esteticaitapema.com.br/',
        type: 'Saúde',
        accessible: true,
        response_time: 980.0,
        status_code: 200,
    },
]
